/*
 * 楽曲検索アプリ用データ
 *
 * 楽曲を追加する場合は PIECES に1件追加してください。
 *   setting:  chamber（独奏・室内楽）/ concerto（協奏曲）/ orchestra（管弦楽）/ band（吹奏楽）
 *   instruments: [楽器キー, 人数]。人数を省略（null）した楽器はセクション扱い（オーケストラ等）。
 *                協奏曲の独奏楽器は3つ目に 'solo' を指定します。
 * 楽器キーは INSTRUMENTS に定義されたものを使います。
 */

const FAMILIES = [
  { key: 'strings',    label: '弦楽器' },
  { key: 'keyboard',   label: '鍵盤楽器' },
  { key: 'woodwind',   label: '木管楽器' },
  { key: 'brass',      label: '金管楽器' },
  { key: 'percussion', label: '打楽器' },
  { key: 'plucked',    label: '撥弦楽器' },
  { key: 'japanese',   label: '和楽器' },
  { key: 'voice',      label: '声楽' },
];

const INSTRUMENTS = {
  violin:        { label: 'ヴァイオリン',       family: 'strings',    aliases: ['バイオリン', 'violin'] },
  viola:         { label: 'ヴィオラ',           family: 'strings',    aliases: ['ビオラ', 'viola'] },
  cello:         { label: 'チェロ',             family: 'strings',    aliases: ['violoncello', 'cello'] },
  contrabass:    { label: 'コントラバス',       family: 'strings',    aliases: ['ダブルベース', 'ベース', 'double bass'] },
  piano:         { label: 'ピアノ',             family: 'keyboard',   aliases: ['piano'] },
  harpsichord:   { label: 'チェンバロ',         family: 'keyboard',   aliases: ['ハープシコード', 'harpsichord', 'cembalo'] },
  celesta:       { label: 'チェレスタ',         family: 'keyboard',   aliases: ['celesta'] },
  piccolo:       { label: 'ピッコロ',           family: 'woodwind',   aliases: ['piccolo'] },
  flute:         { label: 'フルート',           family: 'woodwind',   aliases: ['flute'] },
  oboe:          { label: 'オーボエ',           family: 'woodwind',   aliases: ['oboe'] },
  englishhorn:   { label: 'イングリッシュホルン', family: 'woodwind', aliases: ['コーラングレ', 'english horn', 'cor anglais'] },
  clarinet:      { label: 'クラリネット',       family: 'woodwind',   aliases: ['clarinet'] },
  bassclarinet:  { label: 'バスクラリネット',   family: 'woodwind',   aliases: ['bass clarinet'] },
  bassethorn:    { label: 'バセットホルン',     family: 'woodwind',   aliases: ['basset horn'] },
  bassoon:       { label: 'ファゴット',         family: 'woodwind',   aliases: ['バスーン', 'bassoon', 'fagott'] },
  contrabassoon: { label: 'コントラファゴット', family: 'woodwind',   aliases: ['contrabassoon'] },
  saxophone:     { label: 'サクソフォン',       family: 'woodwind',   aliases: ['サックス', 'saxophone', 'sax'] },
  horn:          { label: 'ホルン',             family: 'brass',      aliases: ['horn'] },
  trumpet:       { label: 'トランペット',       family: 'brass',      aliases: ['trumpet'] },
  cornet:        { label: 'コルネット',         family: 'brass',      aliases: ['cornet'] },
  trombone:      { label: 'トロンボーン',       family: 'brass',      aliases: ['trombone'] },
  euphonium:     { label: 'ユーフォニアム',     family: 'brass',      aliases: ['euphonium'] },
  tuba:          { label: 'チューバ',           family: 'brass',      aliases: ['tuba'] },
  timpani:       { label: 'ティンパニ',         family: 'percussion', aliases: ['timpani'] },
  percussion:    { label: '打楽器（その他）',   family: 'percussion', aliases: ['パーカッション', 'percussion'] },
  harp:          { label: 'ハープ',             family: 'plucked',    aliases: ['harp'] },
  guitar:        { label: 'ギター',             family: 'plucked',    aliases: ['guitar'] },
  koto:          { label: '箏',                 family: 'japanese',   aliases: ['琴', 'こと', 'koto'] },
  shakuhachi:    { label: '尺八',               family: 'japanese',   aliases: ['しゃくはち', 'shakuhachi'] },
  biwa:          { label: '琵琶',               family: 'japanese',   aliases: ['びわ', 'biwa'] },
  voice:         { label: '声楽',               family: 'voice',      aliases: ['歌', 'ボーカル', 'ソプラノ', 'バリトン', 'voice'] },
};

const SETTINGS = {
  chamber:   '独奏・室内楽',
  concerto:  '協奏曲',
  orchestra: '管弦楽',
  band:      '吹奏楽',
};

const ERAS = ['バロック', '古典派', 'ロマン派', '近現代'];

// 管弦楽でよく使う弦楽器セクション
const STRINGS = [['violin', null], ['viola', null], ['cello', null], ['contrabass', null]];

const PIECES = [
  // ---- 独奏 ----
  { title: '無伴奏チェロ組曲 第1番 ト長調', original: 'Cello Suite No. 1 in G major, BWV 1007',
    composer: 'J.S.バッハ', composerOriginal: 'Johann Sebastian Bach', year: 1720, era: 'バロック',
    setting: 'chamber', instruments: [['cello', 1]] },
  { title: '無伴奏ヴァイオリンのためのパルティータ 第2番 ニ短調', original: 'Partita No. 2 in D minor, BWV 1004',
    composer: 'J.S.バッハ', composerOriginal: 'Johann Sebastian Bach', year: 1720, era: 'バロック',
    setting: 'chamber', instruments: [['violin', 1]], note: '終曲「シャコンヌ」で知られる' },
  { title: 'ピアノ・ソナタ 第14番 嬰ハ短調「月光」', original: 'Piano Sonata No. 14, Op. 27 No. 2 "Moonlight"',
    composer: 'ベートーヴェン', composerOriginal: 'Ludwig van Beethoven', year: 1801, era: '古典派',
    setting: 'chamber', instruments: [['piano', 1]] },
  { title: 'バラード 第1番 ト短調', original: 'Ballade No. 1 in G minor, Op. 23',
    composer: 'ショパン', composerOriginal: 'Frédéric Chopin', year: 1835, era: 'ロマン派',
    setting: 'chamber', instruments: [['piano', 1]] },
  { title: '月の光（ベルガマスク組曲 より）', original: 'Clair de lune (Suite bergamasque)',
    composer: 'ドビュッシー', composerOriginal: 'Claude Debussy', year: 1905, era: '近現代',
    setting: 'chamber', instruments: [['piano', 1]] },
  { title: 'シランクス', original: 'Syrinx',
    composer: 'ドビュッシー', composerOriginal: 'Claude Debussy', year: 1913, era: '近現代',
    setting: 'chamber', instruments: [['flute', 1]] },
  { title: 'アルハンブラの思い出', original: 'Recuerdos de la Alhambra',
    composer: 'タレガ', composerOriginal: 'Francisco Tárrega', year: 1896, era: 'ロマン派',
    setting: 'chamber', instruments: [['guitar', 1]] },

  // ---- 二重奏 ----
  { title: '魔王', original: 'Erlkönig, D 328',
    composer: 'シューベルト', composerOriginal: 'Franz Schubert', year: 1815, era: 'ロマン派',
    setting: 'chamber', instruments: [['voice', 1], ['piano', 1]], note: 'ゲーテの詩による歌曲' },
  { title: '愛の挨拶', original: 'Salut d\'amour, Op. 12',
    composer: 'エルガー', composerOriginal: 'Edward Elgar', year: 1888, era: 'ロマン派',
    setting: 'chamber', instruments: [['violin', 1], ['piano', 1]] },
  { title: 'ヴァイオリン・ソナタ イ長調', original: 'Violin Sonata in A major, FWV 8',
    composer: 'フランク', composerOriginal: 'César Franck', year: 1886, era: 'ロマン派',
    setting: 'chamber', instruments: [['violin', 1], ['piano', 1]] },
  { title: 'クラリネット・ソナタ 第1番 ヘ短調', original: 'Clarinet Sonata No. 1 in F minor, Op. 120 No. 1',
    composer: 'ブラームス', composerOriginal: 'Johannes Brahms', year: 1894, era: 'ロマン派',
    setting: 'chamber', instruments: [['clarinet', 1], ['piano', 1]] },
  { title: 'チェロ・ソナタ ト短調', original: 'Cello Sonata in G minor, Op. 19',
    composer: 'ラフマニノフ', composerOriginal: 'Sergei Rachmaninoff', year: 1901, era: 'ロマン派',
    setting: 'chamber', instruments: [['cello', 1], ['piano', 1]] },
  { title: 'フルート・ソナタ', original: 'Flute Sonata, FP 164',
    composer: 'プーランク', composerOriginal: 'Francis Poulenc', year: 1957, era: '近現代',
    setting: 'chamber', instruments: [['flute', 1], ['piano', 1]] },
  { title: '春の海', original: 'Haru no Umi',
    composer: '宮城道雄', composerOriginal: 'Michio Miyagi', year: 1929, era: '近現代',
    setting: 'chamber', instruments: [['koto', 1], ['shakuhachi', 1]] },

  // ---- 三重奏 ----
  { title: 'ケーゲルシュタット・トリオ 変ホ長調', original: 'Trio in E-flat major, K. 498 "Kegelstatt"',
    composer: 'モーツァルト', composerOriginal: 'Wolfgang Amadeus Mozart', year: 1786, era: '古典派',
    setting: 'chamber', instruments: [['clarinet', 1], ['viola', 1], ['piano', 1]] },
  { title: 'ピアノ三重奏曲 第7番 変ロ長調「大公」', original: 'Piano Trio No. 7, Op. 97 "Archduke"',
    composer: 'ベートーヴェン', composerOriginal: 'Ludwig van Beethoven', year: 1811, era: '古典派',
    setting: 'chamber', instruments: [['violin', 1], ['cello', 1], ['piano', 1]] },
  { title: 'ホルン三重奏曲 変ホ長調', original: 'Horn Trio in E-flat major, Op. 40',
    composer: 'ブラームス', composerOriginal: 'Johannes Brahms', year: 1865, era: 'ロマン派',
    setting: 'chamber', instruments: [['horn', 1], ['violin', 1], ['piano', 1]] },

  // ---- 四重奏 ----
  { title: '弦楽四重奏曲 第77番 ハ長調「皇帝」', original: 'String Quartet, Op. 76 No. 3 "Emperor"',
    composer: 'ハイドン', composerOriginal: 'Joseph Haydn', year: 1797, era: '古典派',
    setting: 'chamber', instruments: [['violin', 2], ['viola', 1], ['cello', 1]] },
  { title: '弦楽四重奏曲 第12番 ヘ長調「アメリカ」', original: 'String Quartet No. 12, Op. 96 "American"',
    composer: 'ドヴォルザーク', composerOriginal: 'Antonín Dvořák', year: 1893, era: 'ロマン派',
    setting: 'chamber', instruments: [['violin', 2], ['viola', 1], ['cello', 1]] },
  { title: 'ピアノ四重奏曲 第1番 ト短調', original: 'Piano Quartet No. 1 in G minor, Op. 25',
    composer: 'ブラームス', composerOriginal: 'Johannes Brahms', year: 1861, era: 'ロマン派',
    setting: 'chamber', instruments: [['violin', 1], ['viola', 1], ['cello', 1], ['piano', 1]] },
  { title: '世の終わりのための四重奏曲', original: 'Quatuor pour la fin du temps',
    composer: 'メシアン', composerOriginal: 'Olivier Messiaen', year: 1941, era: '近現代',
    setting: 'chamber', instruments: [['clarinet', 1], ['violin', 1], ['cello', 1], ['piano', 1]] },

  // ---- 五重奏 ----
  { title: 'クラリネット五重奏曲 イ長調', original: 'Clarinet Quintet in A major, K. 581',
    composer: 'モーツァルト', composerOriginal: 'Wolfgang Amadeus Mozart', year: 1789, era: '古典派',
    setting: 'chamber', instruments: [['clarinet', 1], ['violin', 2], ['viola', 1], ['cello', 1]] },
  { title: 'ピアノ五重奏曲 イ長調「ます」', original: 'Piano Quintet in A major, D 667 "Trout"',
    composer: 'シューベルト', composerOriginal: 'Franz Schubert', year: 1819, era: 'ロマン派',
    setting: 'chamber', instruments: [['piano', 1], ['violin', 1], ['viola', 1], ['cello', 1], ['contrabass', 1]] },
  { title: '弦楽五重奏曲 ハ長調', original: 'String Quintet in C major, D 956',
    composer: 'シューベルト', composerOriginal: 'Franz Schubert', year: 1828, era: 'ロマン派',
    setting: 'chamber', instruments: [['violin', 2], ['viola', 1], ['cello', 2]] },
  { title: 'ピアノ五重奏曲 第2番 イ長調', original: 'Piano Quintet No. 2 in A major, Op. 81',
    composer: 'ドヴォルザーク', composerOriginal: 'Antonín Dvořák', year: 1887, era: 'ロマン派',
    setting: 'chamber', instruments: [['piano', 1], ['violin', 2], ['viola', 1], ['cello', 1]] },
  { title: 'クラリネット五重奏曲 ロ短調', original: 'Clarinet Quintet in B minor, Op. 115',
    composer: 'ブラームス', composerOriginal: 'Johannes Brahms', year: 1891, era: 'ロマン派',
    setting: 'chamber', instruments: [['clarinet', 1], ['violin', 2], ['viola', 1], ['cello', 1]] },
  { title: '小室内音楽', original: 'Kleine Kammermusik, Op. 24 No. 2',
    composer: 'ヒンデミット', composerOriginal: 'Paul Hindemith', year: 1922, era: '近現代',
    setting: 'chamber', instruments: [['flute', 1], ['oboe', 1], ['clarinet', 1], ['horn', 1], ['bassoon', 1]],
    note: '木管五重奏' },

  // ---- 六重奏以上 ----
  { title: '兵士の物語', original: 'L\'Histoire du soldat',
    composer: 'ストラヴィンスキー', composerOriginal: 'Igor Stravinsky', year: 1918, era: '近現代',
    setting: 'chamber',
    instruments: [['clarinet', 1], ['bassoon', 1], ['cornet', 1], ['trombone', 1], ['violin', 1], ['contrabass', 1], ['percussion', 1]],
    note: '語り手・俳優を伴う舞台作品' },
  { title: '弦楽八重奏曲 変ホ長調', original: 'String Octet in E-flat major, Op. 20',
    composer: 'メンデルスゾーン', composerOriginal: 'Felix Mendelssohn', year: 1825, era: 'ロマン派',
    setting: 'chamber', instruments: [['violin', 4], ['viola', 2], ['cello', 2]] },
  { title: '八重奏曲 ヘ長調', original: 'Octet in F major, D 803',
    composer: 'シューベルト', composerOriginal: 'Franz Schubert', year: 1824, era: 'ロマン派',
    setting: 'chamber',
    instruments: [['clarinet', 1], ['horn', 1], ['bassoon', 1], ['violin', 2], ['viola', 1], ['cello', 1], ['contrabass', 1]] },
  { title: 'セレナード 第10番 変ロ長調「グラン・パルティータ」', original: 'Serenade No. 10, K. 361 "Gran Partita"',
    composer: 'モーツァルト', composerOriginal: 'Wolfgang Amadeus Mozart', year: 1781, era: '古典派',
    setting: 'chamber',
    instruments: [['oboe', 2], ['clarinet', 2], ['bassethorn', 2], ['horn', 4], ['bassoon', 2], ['contrabass', 1]],
    note: '13管楽器のためのセレナード（作曲年は1781〜84年頃）' },

  // ---- 協奏曲 ----
  { title: '協奏曲集「四季」より「春」', original: 'Le quattro stagioni: La primavera, RV 269',
    composer: 'ヴィヴァルディ', composerOriginal: 'Antonio Vivaldi', year: 1725, era: 'バロック',
    setting: 'concerto', instruments: [['violin', 1, 'solo'], ...STRINGS, ['harpsichord', null]],
    note: '弦楽合奏と通奏低音' },
  { title: 'クラリネット協奏曲 イ長調', original: 'Clarinet Concerto in A major, K. 622',
    composer: 'モーツァルト', composerOriginal: 'Wolfgang Amadeus Mozart', year: 1791, era: '古典派',
    setting: 'concerto',
    instruments: [['clarinet', 1, 'solo'], ['flute', 2], ['bassoon', 2], ['horn', 2], ...STRINGS] },
  { title: 'ヴァイオリン協奏曲 ニ長調', original: 'Violin Concerto in D major, Op. 35',
    composer: 'チャイコフスキー', composerOriginal: 'Pyotr Ilyich Tchaikovsky', year: 1878, era: 'ロマン派',
    setting: 'concerto',
    instruments: [['violin', 1, 'solo'], ['flute', 2], ['oboe', 2], ['clarinet', 2], ['bassoon', 2],
      ['horn', 4], ['trumpet', 2], ['timpani', null], ...STRINGS] },
  { title: 'ピアノ協奏曲 第2番 ハ短調', original: 'Piano Concerto No. 2 in C minor, Op. 18',
    composer: 'ラフマニノフ', composerOriginal: 'Sergei Rachmaninoff', year: 1901, era: 'ロマン派',
    setting: 'concerto',
    instruments: [['piano', 1, 'solo'], ['flute', 2], ['oboe', 2], ['clarinet', 2], ['bassoon', 2],
      ['horn', 4], ['trumpet', 2], ['trombone', 3], ['tuba', 1], ['timpani', null], ['percussion', null], ...STRINGS] },
  { title: 'ノヴェンバー・ステップス', original: 'November Steps',
    composer: '武満徹', composerOriginal: 'Toru Takemitsu', year: 1967, era: '近現代',
    setting: 'concerto',
    instruments: [['biwa', 1, 'solo'], ['shakuhachi', 1, 'solo'], ['flute', null], ['oboe', null], ['clarinet', null],
      ['bassoon', null], ['horn', null], ['trumpet', null], ['trombone', null], ['percussion', null], ['harp', null], ...STRINGS] },

  // ---- 管弦楽 ----
  { title: '交響曲 第5番 ハ短調', original: 'Symphony No. 5 in C minor, Op. 67',
    composer: 'ベートーヴェン', composerOriginal: 'Ludwig van Beethoven', year: 1808, era: '古典派',
    setting: 'orchestra',
    instruments: [['piccolo', 1], ['flute', 2], ['oboe', 2], ['clarinet', 2], ['bassoon', 2], ['contrabassoon', 1],
      ['horn', 2], ['trumpet', 2], ['trombone', 3], ['timpani', null], ...STRINGS] },
  { title: '交響曲 第9番 ホ短調「新世界より」', original: 'Symphony No. 9 in E minor, Op. 95 "From the New World"',
    composer: 'ドヴォルザーク', composerOriginal: 'Antonín Dvořák', year: 1893, era: 'ロマン派',
    setting: 'orchestra',
    instruments: [['flute', 2], ['oboe', 2], ['englishhorn', 1], ['clarinet', 2], ['bassoon', 2],
      ['horn', 4], ['trumpet', 2], ['trombone', 3], ['tuba', 1], ['timpani', null], ['percussion', null], ...STRINGS] },
  { title: 'ボレロ', original: 'Boléro',
    composer: 'ラヴェル', composerOriginal: 'Maurice Ravel', year: 1928, era: '近現代',
    setting: 'orchestra',
    instruments: [['piccolo', null], ['flute', null], ['oboe', null], ['englishhorn', null], ['clarinet', null],
      ['bassclarinet', null], ['bassoon', null], ['contrabassoon', null], ['saxophone', null],
      ['horn', null], ['trumpet', null], ['trombone', null], ['tuba', null], ['timpani', null], ['percussion', null],
      ['celesta', null], ['harp', null], ...STRINGS],
    note: '小太鼓のリズムが全曲を通して続く' },
  { title: '弦楽のためのアダージョ', original: 'Adagio for Strings, Op. 11',
    composer: 'バーバー', composerOriginal: 'Samuel Barber', year: 1936, era: '近現代',
    setting: 'orchestra', instruments: [...STRINGS], note: '弦楽合奏。弦楽四重奏曲 第1番の第2楽章を編曲' },

  // ---- 吹奏楽 ----
  { title: '吹奏楽のための第1組曲 変ホ長調', original: 'First Suite in E-flat for Military Band, Op. 28 No. 1',
    composer: 'ホルスト', composerOriginal: 'Gustav Holst', year: 1909, era: '近現代',
    setting: 'band',
    instruments: [['piccolo', null], ['flute', null], ['oboe', null], ['clarinet', null], ['bassclarinet', null],
      ['bassoon', null], ['saxophone', null], ['cornet', null], ['trumpet', null], ['horn', null],
      ['trombone', null], ['euphonium', null], ['tuba', null], ['contrabass', null], ['timpani', null], ['percussion', null]] },
];
